{
 "title": "Docker hub",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Pulls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "Pulls per hour" }
   ],
   "targets": [
    {
     "expr": "rate(docker_hub_image_pulls_total[1h])",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 17, "y": 0 },
   "targets": [
    { "expr": "docker_hub_image_pulls_total" },
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 1, "x": 23, "y": 0 },
   "targets": [
    { "expr": "docker_hub_image_stars" }
   ]
  },
  {
   "title": "Stars",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "locale", "label": "Stars per hour" }
   ],
   "targets": [
    {
     "expr": "rate(docker_hub_image_stars[1h])",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}